language: java
jdk: openjdk11
dist: bionic
addons:
  apt:
    packages:
      - debhelper
      - make
      - fakeroot
before_cache:
  - rm -f $TRAVIS_BUILD_DIR/.citemp/caches/modules-2/modules-2.lock
  - rm -rf $TRAVIS_BUILD_DIR/.citemp/caches/*/plugin-resolution/
cache:
  directories:
    - $TRAVIS_BUILD_DIR/.citemp/caches/
    - $TRAVIS_BUILD_DIR/.citemp/wrapper

script:
  - ./gradlew --quiet -g .citemp --no-daemon distTar
  - make -f Makefile.deb all

install: true
deploy:
  provider: releases
  api_key:
    secure: WhecNTIDrbgPDO/4kM2VdYu0mn+rq123zR4l6eDmzXLlQL/WpQqZgN7XdMWOS7rjsdsXLZNJReTEY+G5xRVCzLX1GXER4LiNTPa37fFGOaLif1+iBLosV89bk24ta3O83ZKwRGtBVUvqePixh67b7NOwJKUrk+wCG2DwvPhhSr5OjXdBbj8HZkgrFlMEEU/cTcte7sYDVvVZ8eauOMZVc6X+NynYspBW/LOWi/sUVoYXeAabsqaQAgZZPdnhsjUfQeYy2AtE57AxJnOAf86V9M40oJ4j5WeNRa6osENVWcZ7il0pqbstp5lKM8Z9jDB0rwWDusrt37XVmuFoy0/dOsdkoaJfNCtflhl7TnxjvpniUJMzYngDhNEU1s/GiRAzoF3OJ1ajtYq1yH1QoZMM8v6cFfwphjdKCPt3D0epOLPpF5yxCMmi9JV3BmcMiudKnk3J+bsl33zza0dRw5rYMziS6beOz0bjZy+UHVd19CwjLV6xBSTqEPrjHiVFA2bWftiVPdLN1wgowekyeJG5oCfMqQirrIgkuzHvT4zJus1+CPG8vbEQWx+6L/evUxSJd7etVeY1MbQwhRiwc4P+4mhAzoGMusinGDNRCFR0ZaKJ/GPs9X/0lhmD6EXLMf0A29lnBJhIeyV+bKAY8SXguB+o4Xkks9TZF6YqbO3kQmE=
  skip_cleanup: true
  file_glob: true
  file:
    - build/distributions/portal-client-*.tar.gz
    - portal-client_*_all.deb
  draft: false
  overwrite: true
  on:
    tags: true
