server:
  port: 8080
  use-forward-headers: true
  servlet:
    contextPath: /client

spring:
  datasource:
    url: jdbc:postgresql://workdev:5432/ubuntu
    username: ubuntu
    password: ubuntu
    driver: org.postgresql.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      schema: classpath:au/edu/uq/rcc/portal/client/schema.sql
  security:
    oauth2:
      client:
        registration:
          example-realm1:
            client-id: example-realm1-client
            client-secret: 00000000-0000-0000-0000-000000000000
            client-name: example-realm1
          example-realm2:
            client-id: example-realm1-client
            client-secret: 11111111-1111-1111-1111-111111111111
            client-name: example-realm2
        provider:
          example-realm1:
            issuer-uri: https://keycloak.example.com/auth/realms/example-realm1
          example-realm2:
            issuer-uri: https://keycloak.example.com/auth/realms/example-realm2
management:
  server:
    port: 9001
  endpoint:
    health:
      probes:
        enabled: true
